### ISSUE TITLE
Create n_chain, n_iter and n_var helpers

### ISSUE THREAD

**Issue by njtierney** [njtierney/mmcc#33]
For the moment they can wrap:

- `coda::nchain`
- `coda::niter`
- `coda::nvar`

**Comment by samclifford** [comment]
The number of iterations in a chain is a tricky question given thinning may have been applied. We can look at the `mcpar` attribute of an mcmc or mcmc.list object to recover the start, end and thinning amount.

Also perhaps we need to look at an argument for whether or not to aggregate chains so that we can choose to have the total number of iterations across all chains or just the number of iterations within each chain (which will be equal across all chains in the same object).
